# Literature {#intro}

Photogrammetry is an accurate and useful method for generating topographic models. In recent years, Structure from Motion (SfM) algorithms have used imagery from small Unmanned Aerial Vehicles (sUAVs) to generate accurate topographical models. This is a more cost-effective method for generating topography for small areas compared to traditional aerial photogrammetric methods. Extending these general terrain models, recent studies have demonstrated the use of sUAVs and SfM technology in the field of water resources [@Alvarez; @Casella; @Erena; @Huizinga; @Javernick; @Langhammer; @Templin; @Zanutta]. The majority of this work revolves around using UAVs data collection methods to create accurate three-dimensional (3D) topographic models. For example, researchers have monitored braided river channels using photogrammetry [@Javernick] and sUAV images have been used to capture detailed orthoimages of river streambeds and process these images to accurately estimate the particle size distribution of streambed sediments [@Langhammer]. Light Detection and Ranging (LiDAR) has been used in conjunction with sUAV technology to create topo-bathymetric models [@Mandlburger]. LiDAR is a tool that could be used in place of SfM photogrammetry to model shorelines, although LiDAR surveys tend to be more costly as they generally require larger UAVs and more costly sensors. SfM-based photogrammetry has been used to supplement standard sonar collections by collecting data in shallow depths that sonar technology cannot accurately model [@Alvarez]; our method extends this research to above-water areas. Others have used sUAV-based methods to monitor changes in coastline due to wave runup [@Casella] and evaluate water resource infrastructure such as spillways [@Arce]. 

Most sUAV based surveys use a pre-determined grid format for flight patterns over areas where the width and length are of similar magnitude, thus most of the current literature on ground control point spacing discuss and address a grid format for flight patterns and ground control (GCP) placement [@Martinez; @Remondino]. Ground control points are targets set out with known GPS locations before the flight of the UAV that then tie a photogrammetry model (point cloud model) to reality. Although gridded flights are most common for collecting over typical sites, some jobs require long, thin flight paths such as the bathymetric surveys discussed in my project, roads, road cut slopes, levees, or canals [@Carvajal]. The issue of GCP spacing and orientation along long corridors has been research with details of the expected accuracy with different GCP spacing and orientation along a relatively long stretch of road reported [@Ferrer]. My project deals with a similar flight pattern to that presented here, but roads generally follow a regular line, without significant changes, while some reservoir shorelines are erratic and have a more fractal geometry. Long, erratic, shorelines also pose an issue during fieldwork as placing many GCPs may be unrealistic, time consuming, or costly as parts of the shoreline could be inaccessible. The minimal need of GCPs has been researched. The current literature on the precision of point cloud models based on GCP spacing suggests that horizontal (X-, Y-) accuracy is more easily achieved than vertical (Z-) accuracy [@Skarlatos]. Vertical (Z-) accuracy is of the utmost important when creating bathymetric maps as storage capacity curves rely on volumetric calculations of the calculated point cloud, thus my project will look into the precision in the X-, Y-and Z-direction of point clouds produced with varying amounts of GCPs along a shoreline, with a special emphasis on the Z-direction precision. Other factors will be tested to find how those factors effect the shoreline model, including masking water from the images and the effects of mistagged ground control points.

