--- 
title: "Measuring Precision between Point Clouds based on Different Parameters"
author: "Izaak Cooper"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: ""
---

# Introduction

The process of creating three dimensional (3D) models from a collection of two dimensional (2D) images is called photogrammetry. Photogrammetry has been used to model small historical artifacts, structures, and topography. Drones have become an important tool in photogrammetry and topographic modeling in recent years as the combination of these tools provides a relatively cheap alternative to LiDAR when characterizing specific sites. Topographic modeling is useful in multiple fields, and is becoming more widely used in water resources. One specific type of topographic modeling is bathymetry mapping. Bathymetry mapping is topographic modeling of the floor of oceans, seas, lakes, and reservoirs. Bathymetry mapping at reservoirs is usually accomplished through the use of sonar technology, but if the site is not inundated photogrammetry can be used to model the floor of a reservoir. Sonar cannot record the shallower depths of a reservoir and most reservoirs are not at full pool year-round. Since reservoirs are not always at full pool and shallower depths cannot be modeled via sonar some data is missing and a full pool bathymetric map cannot be created. A photogrammetry survey using drones could "finish" the sonar data by modeling the shoreline. This book will test the efficacy of shoreline modeling and the issues associated with modeling shorelines using photogrammetry and drones.

```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
```